# Generated by Django 3.2.6 on 2021-08-21 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0002_auto_20210821_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='quote_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
